# Change these first
owner: Avrean-Srl # Your GitHub organization or username, where this repository lives
repo: redergo-upptime # The name of this repository

sites:
  - name: Redergo
    url: https://redergo.com
  - name: Consorzio Vadò
    url: https://consorziovado.com
  - name: Sasp
    url: https://www.arrampicata.com
  - name: 4foodies
    url: http://4foodies.it
  - name: Hexaquotes
    url: https://hexaquotes.avrean.net
  - name: Consorzio Vadò (duplicato corretto)
    url: https://consorziovado.com
  - name: 4foodies (corretto)
    url: https://www.4foodies.it
  - name: Algo Group
    url: https://www.algogroup.net
  - name: Alice Scagliola Nutrizionista
    url: https://alicescagliolanutrizionista.com
  - name: Images Algo
    url: https://images.algo.it
  - name: Foto Attualità Cesni
    url: https://fotoattualitacesni.com
  - name: Blugestiam
    url: https://blugestiam.com
  - name: Online Service
    url: https://www.onlineservice.it
  - name: Photop
    url: https://photop.it
  - name: Dropper AI
    url: https://www.dropper.ai
  - name: Dropper AI Dashboard
    url: https://dashboard.dropper.ai/login
  - name: Orologi Aeronautica
    url: https://orologiaeronautica.it
  - name: Honpe
    url: https://www.honpe.it
    
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /redergo-upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Redergo-Status
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
