# Change these first
owner: Avrean-Srl # Your GitHub organization or username, where this repository lives
repo: redergo-upptime # The name of this repository

sites:
  - name: 4foodies
    url: https://www.4foodies.it
  - name: Add Skills
    url: https://addskills.it
  - name: Alice Scagliola Nutrizionista
    url: https://alicescagliolanutrizionista.com
  - name: Algo Group
    url: https://www.algogroup.net
  - name: Arkema
    url: https://www.arkema.it
  - name: Au Petit Bonheur
    url: https://aupetitbonheur.org
  - name: Blugestiam
    url: https://blugestiam.com
    __dangerous__insecure: true
  - name: Bursi
    url: https://bursi.it
  - name: Capone Costruzioni
    url: https://caponecostruzioni.com
    __dangerous__insecure: true
  - name: Consorzio Terna
    url: https://consorzioterna.it
  - name: Consorzio Vadò
    url: https://consorziovado.com
  - name: Dropper AI
    url: https://www.dropper.ai
  - name: Dropper AI Dashboard
    url: https://dashboard.dropper.ai/login
  - name: Enercade
    url: https://enercade.com
  - name: Foto Attualità Cesni
    url: https://fotoattualitacesni.com
  - name: Galievr
    url: https://galievr.it
  - name: Grande Marvin
    url: https://grandemarvin.com
    __dangerous__insecure: true
  - name: Hexaquotes
    url: https://hexaquotes.avrean.net
  - name: Honpe
    url: https://www.honpe.it
  - name: Images Algo
    url: https://images.algo.it
  - name: Obertosrl
    url: https://obertosrl.it
    __dangerous__insecure: true
  - name: Online Service
    url: https://www.onlineservice.it
  - name: Orologi Aeronautica
    url: https://orologiaeronautica.it
  - name: Photop
    url: https://photop.it
  - name: Pixlex
    url: https://pixlex.it
    __dangerous__insecure: true
  - name: Quercetti Store
    url: https://www.quercettistore.com/it
  - name: Rekupero
    url: https://www.rekupero.it
    __dangerous__insecure: true
  - name: Riadk
    url: https://riadk.com
  - name: Sasp
    url: https://www.arrampicata.com
  - name: Top Gear Italia
    url: https://topgearitalia.com


    
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /redergo-upptime
  logoUrl: https://www.redergo.com/img/logo-black.svg
  name: Redergo-Status
  introTitle: "**Redergo** Controllo status siti web."
  introMessage: I controlli vengono effettuati ogni 5 minuti. 
  navbar:
    - title: Status
      href: /
    - title: Redergo Website
      href: https://www.redergo.com

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
